from . import hero_section
from . import about
from . import category
from . import contact_boxes
from . import brand
from . import home
from . import label_content
from . import feature
from . import client
from . import contact_us
from . import mail
from . import Blog
from . import content
from . import gallery
from . import box
from . import description